server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
